(eval-when-compile    (require 'color-theme))
(defun color-theme-alex ()
  "Color theme by alexd, created 2010-05-03."
  (interactive)
  (color-theme-install
   '(my-color-theme
     ((background-color . "gray2")
      (background-mode . dark)
      (border-color . "gray2")
      (cursor-color . "gray37")
      (foreground-color . "AntiqueWhite3"))
     ((align-highlight-change-face . highlight)
      (align-highlight-nochange-face . secondary-selection)
      (apropos-keybinding-face . underline)
      (apropos-label-face italic variable-pitch)
      (apropos-match-face . match)
      (apropos-property-face . bold-italic)
      (apropos-symbol-face . bold)
      (compilation-message-face . underline)
      (hl-line-face . hl-line)
      (ispell-highlight-face . isearch)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (org-goto-interface . outline)
      (org-remember-interactive-interface . refile)
      (php-default-face . default)
      (tags-tag-face . default)
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "gray2" :foreground "AntiqueWhite3" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "apple" :family "Monaco"))))
     (better-fringes-bitmap ((t (:foreground "khaki"))))
     (better-fringes-important-bitmap ((t (:foreground "red"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (bookmark-menu-heading ((t (:foreground "#a5c261"))))
     (border ((t (nil))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t))))
     (change-log-acknowledgement ((t (:foreground "#444"))))
     (change-log-conditionals ((t (:foreground "LightGoldenrod"))))
     (change-log-date ((t (:foreground "darkkhaki"))))
     (change-log-email ((t (:foreground "LightGoldenrod"))))
     (change-log-file ((t (:foreground "LightSkyBlue"))))
     (change-log-function ((t (:foreground "LightGoldenrod"))))
     (change-log-list ((t (:foreground "#949c8b"))))
     (change-log-name ((t (:foreground "#6d9cbe"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "cyan1"))))
     (compilation-column-number ((t (:foreground "#a5c261"))))
     (compilation-error ((t (:bold t :weight bold :foreground "Pink"))))
     (compilation-info ((t (:bold t :foreground "Green1" :weight bold))))
     (compilation-line-number ((t (:foreground "LightGoldenrod"))))
     (compilation-warning ((t (:bold t :foreground "Orange" :weight bold))))
     (completions-annotations ((t (:italic t :slant italic))))
     (completions-common-part ((t (:family "Monaco" :foundry "apple" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "AntiqueWhite3" :background "gray2" :stipple nil :height 120))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cursor ((t (:background "gray37"))))
     (custom-button ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-mouse ((t (:background "grey90" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-button-pressed-unraised ((t (:underline t :foreground "violet"))))
     (custom-button-unraised ((t (:underline t))))
     (custom-changed ((t (:background "blue1" :foreground "white"))))
     (custom-comment ((t (:background "dim gray"))))
     (custom-comment-tag ((t (:foreground "gray80"))))
     (custom-documentation ((t (nil))))
     (custom-face-tag ((t (:bold t :weight bold :foreground "light blue"))))
     (custom-group-tag ((t (:bold t :family "Sans Serif" :foreground "light blue" :weight bold :height 1.2))))
     (custom-group-tag-1 ((t (:bold t :family "Sans Serif" :foreground "pink" :weight bold :height 1.2))))
     (custom-invalid ((t (:background "red1" :foreground "yellow1"))))
     (custom-link ((t (:underline t :foreground "cyan1"))))
     (custom-modified ((t (:background "blue1" :foreground "white"))))
     (custom-rogue ((t (:background "black" :foreground "pink"))))
     (custom-saved ((t (:underline t))))
     (custom-set ((t (:background "white" :foreground "blue1"))))
     (custom-state ((t (:foreground "lime green"))))
     (custom-themed ((t (:background "blue1" :foreground "white"))))
     (custom-variable-button ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag ((t (:bold t :foreground "light blue" :weight bold))))
     (custom-visibility ((t (:underline t :foreground "cyan1" :height 0.8))))
     (diff-added ((t (nil))))
     (diff-changed ((t (nil))))
     (diff-context ((t (:foreground "grey70"))))
     (diff-file-header ((t (:bold t :background "grey60" :weight bold))))
     (diff-function ((t (:background "grey45"))))
     (diff-header ((t (:background "grey45"))))
     (diff-hunk-header ((t (:background "grey45"))))
     (diff-index ((t (:bold t :weight bold :background "grey60"))))
     (diff-indicator-added ((t (nil))))
     (diff-indicator-changed ((t (nil))))
     (diff-indicator-removed ((t (nil))))
     (diff-nonexistent ((t (:bold t :weight bold :background "grey60"))))
     (diff-refine-change ((t (:background "grey60"))))
     (diff-removed ((t (nil))))
     (dired-directory ((t (:foreground "LightSkyBlue"))))
     (dired-flagged ((t (:bold t :weight bold :foreground "Pink"))))
     (dired-header ((t (:foreground "#a5c261"))))
     (dired-ignored ((t (:foreground "grey70"))))
     (dired-mark ((t (:foreground "#6d9cbe"))))
     (dired-marked ((t (:bold t :weight bold :foreground "Pink"))))
     (dired-perm-write ((t (:foreground "#444"))))
     (dired-symlink ((t (:foreground "#949c8b"))))
     (dired-warning ((t (:bold t :weight bold :foreground "Pink"))))
     (doc-title-1-face ((t (:bold t :family "Sans Serif" :foreground "brown3" :weight bold :height 1.2))))
     (doc-title-2-face ((t (:bold t :family "Sans Serif" :foreground "DeepPink2" :weight bold :height 1.1))))
     (doc-title-3-face ((t (:bold t :foreground "sienna3" :weight bold))))
     (doc-title-4-face ((t (:foreground "burlywood3"))))
     (dropdown-list-face ((t (:family "Monaco" :foundry "apple" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :stipple nil :background "lightyellow" :foreground "black" :height 120))))
     (dropdown-list-selection-face ((t (:foreground "black" :stipple nil :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "apple" :family "Monaco" :background "purple" :height 120))))
     (ediff-current-diff-A ((t (:background "pale green" :foreground "firebrick"))))
     (ediff-current-diff-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
     (ediff-current-diff-B ((t (:background "Yellow" :foreground "DarkOrchid"))))
     (ediff-current-diff-C ((t (:background "Pink" :foreground "Navy"))))
     (ediff-even-diff-A ((t (:background "light grey" :foreground "Black"))))
     (ediff-even-diff-Ancestor ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-B ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-C ((t (:background "light grey" :foreground "Black"))))
     (ediff-fine-diff-A ((t (:background "sky blue" :foreground "Navy"))))
     (ediff-fine-diff-Ancestor ((t (:background "Green" :foreground "Black"))))
     (ediff-fine-diff-B ((t (:background "cyan" :foreground "Black"))))
     (ediff-fine-diff-C ((t (:background "Turquoise" :foreground "Black"))))
     (ediff-odd-diff-A ((t (:background "Grey" :foreground "White"))))
     (ediff-odd-diff-Ancestor ((t (:background "gray40" :foreground "cyan3"))))
     (ediff-odd-diff-B ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-C ((t (:background "Grey" :foreground "White"))))
     (epa-field-body ((t (:italic t :foreground "turquoise" :slant italic))))
     (epa-field-name ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
     (epa-mark ((t (:bold t :foreground "orange" :weight bold))))
     (epa-string ((t (:foreground "lightyellow"))))
     (epa-validity-disabled ((t (:italic t :slant italic))))
     (epa-validity-high ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
     (epa-validity-low ((t (:italic t :slant italic))))
     (epa-validity-medium ((t (:italic t :foreground "PaleTurquoise" :slant italic))))
     (escape-glyph ((t (:foreground "cyan"))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (fixed-pitch ((t (:family "Monospace"))))
     (flymake-errline ((t (:background "Firebrick4"))))
     (flymake-warnline ((t (:background "DarkBlue"))))
     (flyspell-duplicate ((t (:bold t :foreground "Gold3" :underline t :weight bold))))
     (flyspell-incorrect ((t (:bold t :foreground "OrangeRed" :underline t :weight bold))))
     (font-lock-builtin-face ((t (:foreground "LightSteelBlue"))))
     (font-lock-comment-delimiter-face ((t (:foreground "#444"))))
     (font-lock-comment-face ((t (:foreground "#444"))))
     (font-lock-constant-face ((t (:foreground "#6d9cbe"))))
     (font-lock-doc-face ((t (:foreground "darkkhaki"))))
     (font-lock-function-name-face ((t (:foreground "LightSkyBlue"))))
     (font-lock-keyword-face ((t (:foreground "#949c8b"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "LightSteelBlue"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-string-face ((t (:foreground "darkkhaki"))))
     (font-lock-type-face ((t (:foreground "#a5c261"))))
     (font-lock-variable-name-face ((t (:foreground "LightGoldenrod"))))
     (font-lock-warning-face ((t (:bold t :foreground "Pink" :weight bold))))
     (fringe ((t (:background "gray2"))))
     (header-line ((t (:box (:line-width -1 :style released-button) :background "grey20" :foreground "grey90" :box nil))))
     (help-argument-name ((t (:italic t :slant italic))))
     (hi-mumamo-black-b ((t (:bold t :underline t :weight bold))))
     (hi-mumamo-blue ((t (:underline "light blue"))))
     (hi-mumamo-blue-b ((t (:bold t :underline "blue1" :weight bold))))
     (hi-mumamo-green ((t (:underline "green1"))))
     (hi-mumamo-green-b ((t (:bold t :underline "green1" :weight bold))))
     (hi-mumamo-pink ((t (:underline "pink"))))
     (hi-mumamo-red-b ((t (:bold t :underline "red1" :weight bold))))
     (hi-mumamo-yellow ((t (:underline "yellow1"))))
     (highlight ((t (:background "darkolivegreen"))))
     (hl-line ((t (:background "gray9"))))
     (ido-first-match ((t (:bold t :weight bold))))
     (ido-incomplete-regexp ((t (:bold t :weight bold :foreground "Pink"))))
     (ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
     (ido-only-match ((t (:foreground "ForestGreen"))))
     (ido-subdir ((t (:foreground "red1"))))
     (info-header-node ((t (:italic t :bold t :weight bold :slant italic :foreground "brown"))))
     (info-header-xref ((t (:foreground "cyan1" :underline t))))
     (info-menu-header ((t (:bold t :family "Sans Serif" :weight bold))))
     (info-menu-star ((t (:foreground "red1"))))
     (info-node ((t (:italic t :bold t :foreground "brown" :slant italic :weight bold))))
     (info-title-1 ((t (:bold t :weight bold :family "Sans Serif" :height 1.728))))
     (info-title-2 ((t (:bold t :family "Sans Serif" :weight bold :height 1.44))))
     (info-title-3 ((t (:bold t :weight bold :family "Sans Serif" :height 1.2))))
     (info-title-4 ((t (:bold t :family "Sans Serif" :weight bold))))
     (info-xref ((t (:underline t :foreground "cyan1"))))
     (info-xref-visited ((t (:foreground "violet" :underline t))))
     (isearch ((t (:background "palevioletred2" :foreground "brown4"))))
     (isearch-fail ((t (:background "red4"))))
     (italic ((t (:italic t :slant italic))))
     (lazy-highlight ((t (:background "paleturquoise4"))))
     (link ((t (:foreground "cyan1" :underline t))))
     (link-visited ((t (:underline t :foreground "violet"))))
     (magit-branch ((t (:bold t :weight bold))))
     (magit-diff-add ((t (:foreground "yellowgreen"))))
     (magit-diff-del ((t (:foreground "firebrick3"))))
     (magit-diff-file-header ((t (nil))))
     (magit-diff-hunk-header ((t (:italic t :slant italic))))
     (magit-diff-none ((t (nil))))
     (magit-header ((t (nil))))
     (magit-item-highlight ((t (:background "gray9"))))
     (magit-item-mark ((t (:foreground "orange"))))
     (magit-log-head-label ((t (:background "DarkGreen"))))
     (magit-log-tag-label ((t (:background "DarkGoldenRod"))))
     (magit-section-title ((t (:bold t :weight bold))))
     (match ((t (:background "RoyalBlue3"))))
     (menu ((t (nil))))
     (message-cited-text ((t (:foreground "LightPink1"))))
     (message-header-cc ((t (:bold t :foreground "chartreuse1" :weight bold))))
     (message-header-name ((t (:foreground "green"))))
     (message-header-newsgroups ((t (:italic t :bold t :foreground "yellow" :slant italic :weight bold))))
     (message-header-other ((t (:foreground "VioletRed1"))))
     (message-header-subject ((t (:foreground "OliveDrab1"))))
     (message-header-to ((t (:bold t :foreground "DarkOliveGreen1" :weight bold))))
     (message-header-xheader ((t (:foreground "DeepSkyBlue1"))))
     (message-mml ((t (:foreground "MediumSpringGreen"))))
     (message-separator ((t (:foreground "LightSkyBlue1"))))
     (minibuffer-prompt ((t (:foreground "cyan"))))
     (mlinks-link ((t (:underline t :foreground "cyan1"))))
     (mode-line ((t (:background "grey75" :foreground "black" :box (:line-width -1 :style released-button)))))
     (mode-line-buffer-id ((t (:bold t :weight bold))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "grey30" :foreground "grey80" :box (:line-width -1 :color "grey40" :style nil) :weight light))))
     (mouse ((t (nil))))
     (mumamo-background-chunk-major ((t (:background "gray2"))))
     (mumamo-background-chunk-submode1 ((t (:background "gray10"))))
     (mumamo-background-chunk-submode2 ((t (:background "dark green"))))
     (mumamo-background-chunk-submode3 ((t (:background "dark green"))))
     (mumamo-background-chunk-submode4 ((t (:background "dark green"))))
     (mumamo-border-face-in ((t (:italic t :bold t :foreground "LightSteelBlue" :underline t :slant italic :weight bold))))
     (mumamo-border-face-out ((t (:italic t :bold t :foreground "LightSteelBlue" :slant italic :weight bold))))
     (next-error ((t (:foreground "AntiqueWhite2" :background "#3d3d3d"))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (ns-working-text-face ((t (:underline t))))
     (nxml-attribute-colon ((t (nil))))
     (nxml-attribute-local-name ((t (:foreground "LightGoldenrod"))))
     (nxml-attribute-prefix ((t (:foreground "LightSteelBlue"))))
     (nxml-attribute-value ((t (:foreground "darkkhaki"))))
     (nxml-attribute-value-delimiter ((t (:foreground "darkkhaki"))))
     (nxml-cdata-section-CDATA ((t (:foreground "LightSteelBlue"))))
     (nxml-cdata-section-content ((t (nil))))
     (nxml-cdata-section-delimiter ((t (nil))))
     (nxml-char-ref-delimiter ((t (:foreground "#6d9cbe"))))
     (nxml-char-ref-number ((t (:foreground "#6d9cbe"))))
     (nxml-comment-content ((t (:foreground "#444"))))
     (nxml-comment-delimiter ((t (:foreground "#444"))))
     (nxml-delimited-data ((t (:foreground "darkkhaki"))))
     (nxml-delimiter ((t (nil))))
     (nxml-element-colon ((t (nil))))
     (nxml-element-local-name ((t (:foreground "LightSkyBlue"))))
     (nxml-element-prefix ((t (:foreground "LightSteelBlue"))))
     (nxml-entity-ref-delimiter ((t (:foreground "#6d9cbe"))))
     (nxml-entity-ref-name ((t (:foreground "#6d9cbe"))))
     (nxml-glyph ((t (:background "light grey" :foreground "black" :slant normal :weight normal))))
     (nxml-hash ((t (:foreground "LightSteelBlue"))))
     (nxml-heading ((t (:bold t :weight bold))))
     (nxml-markup-declaration-delimiter ((t (nil))))
     (nxml-name ((t (:foreground "LightSteelBlue"))))
     (nxml-namespace-attribute-colon ((t (nil))))
     (nxml-namespace-attribute-prefix ((t (:foreground "LightGoldenrod"))))
     (nxml-namespace-attribute-value ((t (:foreground "darkkhaki"))))
     (nxml-namespace-attribute-value-delimiter ((t (:foreground "darkkhaki"))))
     (nxml-namespace-attribute-xmlns ((t (:foreground "LightSteelBlue"))))
     (nxml-outline-active-indicator ((t (:stipple nil :background "gray2" :foreground "AntiqueWhite3" :inverse-video nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "apple" :family "Monaco" :box 1 :height 120))))
     (nxml-outline-ellipsis ((t (:bold t :family "Monaco" :foundry "apple" :width normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "AntiqueWhite3" :background "gray2" :stipple nil :weight bold :height 120))))
     (nxml-outline-indicator ((t (:family "Monaco" :foundry "apple" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "AntiqueWhite3" :background "gray2" :stipple nil :height 120))))
     (nxml-processing-instruction-content ((t (:foreground "darkkhaki"))))
     (nxml-processing-instruction-delimiter ((t (nil))))
     (nxml-processing-instruction-target ((t (:foreground "#949c8b"))))
     (nxml-prolog-keyword ((t (:foreground "#949c8b"))))
     (nxml-prolog-literal-content ((t (:foreground "darkkhaki"))))
     (nxml-prolog-literal-delimiter ((t (:foreground "darkkhaki"))))
     (nxml-ref ((t (:foreground "#6d9cbe"))))
     (nxml-tag-delimiter ((t (nil))))
     (nxml-tag-slash ((t (nil))))
     (nxml-text ((t (nil))))
     (org-agenda-clocking ((t (:background "SkyBlue4"))))
     (org-agenda-column-dateline ((t (:family "Monaco" :weight normal :slant normal :underline nil :strike-through nil :background "grey90" :height 120))))
     (org-agenda-date ((t (:foreground "LightSkyBlue"))))
     (org-agenda-date-today ((t (:italic t :bold t :foreground "LightSkyBlue" :slant italic :weight bold))))
     (org-agenda-date-weekend ((t (:bold t :foreground "LightSkyBlue" :weight bold))))
     (org-agenda-dimmed-todo-face ((t (:foreground "grey50"))))
     (org-agenda-done ((t (:foreground "PaleGreen"))))
     (org-agenda-restriction-lock ((t (:background "skyblue4"))))
     (org-agenda-structure ((t (:foreground "LightSkyBlue"))))
     (org-archived ((t (:foreground "grey70"))))
     (org-block ((t (:foreground "grey70"))))
     (org-checkbox ((t (:bold t :weight bold))))
     (org-checkbox-statistics-done ((t (:bold t :weight bold :foreground "ForestGreen"))))
     (org-checkbox-statistics-todo ((t (:bold t :weight bold :foreground "Red1"))))
     (org-clock-overlay ((t (:background "SkyBlue4"))))
     (org-code ((t (:foreground "grey70"))))
     (org-column ((t (:background "grey90" :strike-through nil :underline nil :slant normal :weight normal :height 120 :family "Monaco"))))
     (org-column-title ((t (:bold t :background "grey30" :underline t :weight bold))))
     (org-date ((t (:foreground "Cyan" :underline t))))
     (org-done ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (org-drawer ((t (:foreground "LightSkyBlue"))))
     (org-ellipsis ((t (:foreground "LightGoldenrod" :underline t))))
     (org-footnote ((t (:foreground "Cyan" :underline t))))
     (org-formula ((t (:foreground "chocolate1"))))
     (org-headline-done ((t (:foreground "LightSalmon"))))
     (org-hide ((t (:foreground "black"))))
     (org-latex-and-export-specials ((t (:foreground "burlywood"))))
     (org-level-1 ((t (:foreground "LightSkyBlue"))))
     (org-level-2 ((t (:foreground "LightGoldenrod"))))
     (org-level-3 ((t (:foreground "#949c8b"))))
     (org-level-4 ((t (:foreground "#444"))))
     (org-level-5 ((t (:foreground "#a5c261"))))
     (org-level-6 ((t (:foreground "#6d9cbe"))))
     (org-level-7 ((t (:foreground "LightSteelBlue"))))
     (org-level-8 ((t (:foreground "darkkhaki"))))
     (org-link ((t (:foreground "Cyan" :underline t))))
     (org-meta-line ((t (:foreground "#444"))))
     (org-mode-line-clock ((t (:box (:line-width -1 :style released-button) :foreground "black" :background "grey75"))))
     (org-property-value ((t (nil))))
     (org-quote ((t (:foreground "grey70"))))
     (org-scheduled ((t (:foreground "PaleGreen"))))
     (org-scheduled-previously ((t (:foreground "chocolate1"))))
     (org-scheduled-today ((t (:foreground "PaleGreen"))))
     (org-sexp-date ((t (:foreground "Cyan"))))
     (org-special-keyword ((t (:foreground "LightSalmon"))))
     (org-table ((t (:foreground "LightSkyBlue"))))
     (org-tag ((t (:bold t :weight bold))))
     (org-target ((t (:underline t))))
     (org-time-grid ((t (:foreground "LightGoldenrod"))))
     (org-todo ((t (:bold t :foreground "Red1" :weight bold))))
     (org-upcoming-deadline ((t (:foreground "chocolate1"))))
     (org-verbatim ((t (:foreground "grey70"))))
     (org-verse ((t (:foreground "grey70"))))
     (org-warning ((t (:bold t :weight bold :foreground "Pink"))))
     (outline-1 ((t (:foreground "LightSkyBlue"))))
     (outline-2 ((t (:foreground "LightGoldenrod"))))
     (outline-3 ((t (:foreground "#949c8b"))))
     (outline-4 ((t (:foreground "#444"))))
     (outline-5 ((t (:foreground "#a5c261"))))
     (outline-6 ((t (:foreground "#6d9cbe"))))
     (outline-7 ((t (:foreground "LightSteelBlue"))))
     (outline-8 ((t (:foreground "darkkhaki"))))
     (query-replace ((t (:foreground "brown4" :background "palevioletred2"))))
     (region ((t (:background "#3d3d3d" :foreground "AntiqueWhite2"))))
     (rng-error ((t (:bold t :weight bold :foreground "Pink"))))
     (rngalt-validation-header-bottom ((t (:background "RGB:87/CE/FA" :foreground "white"))))
     (rngalt-validation-header-top ((t (:background "white" :foreground "RGB:87/CE/FA"))))
     (scroll-bar ((t (nil))))
     (secondary-selection ((t (:background "SkyBlue4"))))
     (sgml-namespace ((t (:foreground "LightSteelBlue"))))
     (sh-escaped-newline ((t (:foreground "darkkhaki"))))
     (sh-heredoc ((t (:bold t :foreground "yellow1" :weight bold))))
     (sh-quoted-exec ((t (:foreground "salmon"))))
     (shadow ((t (:foreground "grey70"))))
     (show-paren-match ((t (:background "OliveDrab"))))
     (show-paren-mismatch ((t (:background "purple" :foreground "white"))))
     (speedbar-button-face ((t (:foreground "green3"))))
     (speedbar-directory-face ((t (:foreground "light blue"))))
     (speedbar-file-face ((t (:foreground "cyan"))))
     (speedbar-highlight-face ((t (:background "sea green"))))
     (speedbar-selected-face ((t (:foreground "red" :underline t))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
     (speedbar-tag-face ((t (:foreground "yellow"))))
     (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:family "Sans Serif" :background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "red1"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (vertical-border ((t (nil))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "dim gray"))))
     (widget-inactive ((t (:foreground "grey70"))))
     (widget-single-line-field ((t (:background "dim gray"))))
     (yas/field-debug-face ((t (nil))))
     (yas/field-highlight-face ((t (:foreground "AntiqueWhite2" :background "#3d3d3d")))))))
(add-to-list 'color-themes '(color-theme-alex  "alex" "Alex Duller"))